language: c++

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake-data cmake
  - sudo apt-get install gfortran

install:
  - mkdir build
  - cd build/
  - cmake -DCMAKE_BUILD_TYPE:STRING=DEBUG -DTriBITS_ENABLE_Fortran:BOOL=ON -DTriBITS_HOSTNAME=travis-ci-server-linux ../
  - make

script:
  - ctest -VV
